version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/article
      - REDIS_URL=redis://redis:6379
      - PORT=8080

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=article
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
volumes:
  postgres-data:
